import { VENUES_ENDPOINT, LOGIN_ENDPOINT, REGISTER_ENDPOINT, BOOK_VENUE_ENDPOINT, CREATE_VENUE_ENDPOINT, DELETE_VENUE_ENDPOINT, getVenueEndpoint } from "./variables";

export { VENUES_ENDPOINT, LOGIN_ENDPOINT, REGISTER_ENDPOINT, BOOK_VENUE_ENDPOINT, CREATE_VENUE_ENDPOINT, DELETE_VENUE_ENDPOINT, getVenueEndpoint };
