import Home from "./home";
import Venues from "./venues";
import Register from "./register/register";
import RegisterFormPage from "./register/registerForm";
import Contact from "./contact";
import ContactSuccess from "./contactSuccess";
import RentOutVenue from "./venueManager/vmPostVenue";
import Profile from "./profile/profile";
import Login from "./login/login";
import LoginComplete from "./login/loginSuccess";
import BookingSuccess from "./bookingSuccess";
import RegistrationComplete from "./register/registerComplete";
import VenueManagerBookings from "./venueManager/vmBookings";
import UpdateVenue from "./venueManager/vmUpdateVenue";
import UpdateProfile from "./profile/updateProfile";
import Venue from "./venue";
import CreateVenueSuccess from "./venueManager/vmPostVenueSuccess";
import UpdateVenueSuccess from "./venueManager/vmUpdateVenueSuccess";
import UpdateProfileSuccess from "./profile/updateProfileSuccess";
import NotFound from "./notFound";

export { Home, Venues, Register, Contact, RentOutVenue, Profile, Login, BookingSuccess, RegisterFormPage, RegistrationComplete, LoginComplete, VenueManagerBookings, UpdateVenue, UpdateProfile, Venue, ContactSuccess, CreateVenueSuccess, UpdateVenueSuccess, UpdateProfileSuccess, NotFound };
